In [2]:
import pandas as pd

In [3]:
cambio = pd.read_csv('cambio.csv')

In [4]:
cambio.head()

,Data,Taxa de câmbio - R$ / US$ - comercial - futuro: vencimento em t+1 - R$ - Bolsa de Valores- Mercadorias e Futuros (BM&FBovespa) - BMF366_FUT1DOL366,Unnamed: 2
0,02/01/2001,1.959736,NaN
1,03/01/2001,1.965246,NaN
2,04/01/2001,1.957205,NaN
3,05/01/2001,1.972200,NaN
4,06/01/2001,NaN,NaN

In [5]:
cambio.head(6)

,Data,Taxa de câmbio - R$ / US$ - comercial - futuro: vencimento em t+1 - R$ - Bolsa de Valores- Mercadorias e Futuros (BM&FBovespa) - BMF366_FUT1DOL366,Unnamed: 2
0,02/01/2001,1.959736,NaN
1,03/01/2001,1.965246,NaN
2,04/01/2001,1.957205,NaN
3,05/01/2001,1.972200,NaN
4,06/01/2001,NaN,NaN
5,07/01/2001,NaN,NaN

In [6]:
cambio.tail()

,Data,Taxa de câmbio - R$ / US$ - comercial - futuro: vencimento em t+1 - R$ - Bolsa de Valores- Mercadorias e Futuros (BM&FBovespa) - BMF366_FUT1DOL366,Unnamed: 2
9277,28/05/2026,5.04944,NaN
9278,29/05/2026,5.07550,NaN
9279,30/05/2026,NaN,NaN
9280,31/05/2026,NaN,NaN
9281,01/06/2026,5.04438,NaN

In [7]:
type(cambio)

pandas.DataFrame

In [8]:
api = 'https://dados.tce.rs.gov.br/dados/municipal/prev-receitas/2026.csv'
dados = pd.read_csv(api)

In [9]:
dados.head()

,ANO,CD_ORGAO,NOME,CD_RECEBIMENTO,CD_CONTA_SG,DS_CONTA_SG,VL_ARRECADADO
0,2026,40100,PM DE AGUDO,380683,11125001010000000000,IPTU - Principal - PROPRIO,-250082.37
1,2026,40100,PM DE AGUDO,380683,11125001010000000000,IPTU - Principal - PROPRIO,1387744.36
2,2026,40100,PM DE AGUDO,380683,11125001020000000000,IPTU - Principal - MDE,-122767.38
3,2026,40100,PM DE AGUDO,380683,11125001020000000000,IPTU - Principal - MDE,681255.97
4,2026,40100,PM DE AGUDO,380683,11125001030000000000,IPTU - Principal - ASPS,454169.06